In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv("E:\\machine learning project\\heart.csv")
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
data.isnull().count

<bound method DataFrame.count of        age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang
0    False  False  False     False  False  False    False    False  False  \
1    False  False  False     False  False  False    False    False  False
2    False  False  False     False  False  False    False    False  False
3    False  False  False     False  False  False    False    False  False
4    False  False  False     False  False  False    False    False  False
..     ...    ...    ...       ...    ...    ...      ...      ...    ...
298  False  False  False     False  False  False    False    False  False
299  False  False  False     False  False  False    False    False  False
300  False  False  False     False  False  False    False    False  False
301  False  False  False     False  False  False    False    False  False
302  False  False  False     False  False  False    False    False  False

     oldpeak  slope     ca   thal  target
0      False  False  False  False   False
1      False  False  False  False   False
2      False  False  False  False   False
3      False  False  False  False   False
4      False  False  False  False   False
..       ...    ...    ...    ...     ...
298    False  False  False  False   False
299    False  False  False  False   False
300    False  False  False  False   False
301    False  False  False  False   False
302    False  False  False  False   False

[303 rows x 14 columns]>

In [7]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [8]:
x=data.drop(columns=["target"],axis=1)
y=data["target"]

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2,test_size=0.2)

In [10]:
classifier=svm.SVC(kernel="linear")

In [11]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [12]:
x_train=classifier.predict(x_train)

In [13]:
accuracy=accuracy_score(x_train,y_train)

In [14]:
print("accuracy of the data",accuracy)

accuracy of the data 0.8429752066115702

In [15]:
import pickle

In [16]:
filename="heart_model.csv"
pickle.dump(classifier,open(filename,"wb"))